/* Fictional, hand-written teaching cases. Classifications are game labels, not protocols. */
const patients = [
['021',72,['Chest discomfort','Difficulty breathing','Dizziness'],'Symptoms started while walking 20 minutes ago.',136,88,100.2,148,92,28,'emergency','Low oxygen, rapid breathing, chest discomfort, and a fast heart rate are multiple high-priority warning signs in this simulated case.'],
['104',19,['Sprained wrist','Mild swelling'],'Fell during a basketball game; alert and speaking comfortably.',78,99,98.4,118,74,15,'stable','The fictional patient is alert with comfortable breathing and otherwise steady observations.'],
['337',48,['Persistent abdominal discomfort','Nausea'],'Symptoms have continued since this morning without sudden change.',102,97,99.4,132,82,19,'urgent','The ongoing discomfort and mildly elevated heart rate support prompt evaluation in this simulated case.'],
['059',66,['Sudden confusion','Trouble speaking'],'A family member noticed the change about 15 minutes ago.',88,96,98.6,172,94,18,'emergency','Sudden neurological warning signs are high-priority clues in this fictional scenario.'],
['218',31,['Sore throat','Runny nose'],'Symptoms began yesterday; patient is drinking fluids and comfortable.',82,98,99.1,121,76,16,'stable','Comfortable breathing, normal oxygen level, and a mild, gradual scenario support the stable game category.'],
['410',55,['Lightheadedness','Weakness'],'Reports poor appetite for two days and feels faint when standing.',116,95,100.4,92,58,24,'urgent','Low blood pressure with weakness and a faster pulse makes this fictional case more urgent.'],
['077',43,['Severe bleeding from cut','Pale appearance'],'A deep kitchen cut continues bleeding despite pressure.',124,94,98.2,86,54,26,'emergency','Uncontrolled severe bleeding and low pressure are immediate warning signs in this simulation.'],
['192',28,['Headache','Sensitivity to light'],'Headache is similar to past episodes and started gradually.',74,99,98.7,126,80,14,'stable','The scenario is gradual with steady fictional observations and no added warning signs.'],
['265',83,['Fever','New cough','Fatigue'],'Symptoms worsened over three days; patient is awake and conversing.',108,93,102.8,138,78,22,'urgent','Fever, lower oxygen saturation, and increased breathing rate make this a prompt-evaluation case.'],
['146',38,['Brief palpitations'],'Felt a short flutter after several coffees; now comfortable.',110,99,98.5,130,84,17,'stable','One mildly unusual observation alone does not automatically make a case an emergency; the patient is now comfortable with reassuring fictional signs.'],
['301',61,['Difficulty breathing','Blue-tinged lips'],'Breathing became suddenly much harder while resting.',142,84,98.9,154,88,32,'emergency','Very low oxygen saturation, rapid breathing, and visible breathing difficulty are multiple emergency clues in this simulation.'],
['085',12,['Fever','Ear discomfort'],'Parent reports reduced appetite but child is awake and drinking.',104,98,101.1,106,68,20,'urgent','Fever and reduced intake call for prompt evaluation in this fictional teaching case.'],
['244',52,['Back pain after lifting'],'Pain began after moving boxes; no weakness or breathing symptoms.',84,99,98.3,128,79,16,'stable','A clear minor mechanism with steady fictional vital signs supports stable triage.'],
['395',70,['Fainted briefly','Irregular pulse feeling'],'Collapsed while standing in line, then regained awareness.',44,96,98.1,98,60,20,'emergency','Loss of consciousness and an extremely low heart rate are high-priority clues in this fictional case.'],
['129',24,['Vomiting','Dizziness'],'Unable to keep fluids down since last night.',118,97,99.7,108,70,22,'urgent','Persistent vomiting with dizziness and a fast pulse suggests prompt attention in the game.'],
['472',46,['Red, itchy rash'],'Rash started after gardening; no facial swelling or breathing difficulty.',76,99,98.2,120,76,15,'stable','The fictional symptoms are localized and vital signs are steady, with no breathing warning signs.'],
['016',58,['Chest pressure','Sweating'],'Pressure began at rest 10 minutes ago and is increasing.',118,91,98.4,160,94,26,'emergency','Increasing chest pressure, sweating, lower oxygen, and fast breathing are combined warning signs in this simulation.'],
['223',35,['Ankle pain','Unable to bear weight'],'Twisted ankle on stairs; no head injury.',90,99,98.5,124,78,17,'urgent','The inability to bear weight needs prompt assessment, despite otherwise stable fictional observations.'],
['361',76,['Sleepiness','Slow breathing'],'Caregiver says patient is difficult to wake after an unknown medication mix-up.',52,90,97.8,102,64,8,'emergency','Reduced responsiveness, slow breathing, low oxygen, and a very slow heart rate are emergency clues here.'],
['098',41,['Mild dizziness'],'Skipped breakfast and feels better after water.',92,99,98.4,116,72,16,'stable','Symptoms are improving and the rest of the fictional picture is reassuring.'],
['284',63,['Leg swelling','New shortness of breath'],'Breathing is uncomfortable when walking across the room.',112,92,99.0,146,86,25,'urgent','New breathlessness, reduced oxygen saturation, and increased respiratory rate support prompt evaluation.'],
['417',17,['Panic','Tingling fingers'],'Symptoms started during a stressful presentation; symptoms easing with slow breathing.',122,99,98.6,134,82,26,'stable','A higher heart and breathing rate can occur in context; improving symptoms and normal oxygen make this stable in the fictional game.'],
['150',69,['Sudden severe headache','Vomiting'],'Describes this as unlike previous headaches and abruptly started.',96,97,98.8,188,102,20,'emergency','Sudden severe symptoms with vomiting and very high blood pressure are high-priority warnings in this simulation.'],
['326',50,['Painful urination','Low fever'],'Symptoms started yesterday; patient is drinking fluids.',96,98,100.8,126,80,18,'urgent','Ongoing symptoms with fever are categorized for prompt evaluation in this fictional case.'],
['071',33,['Small finger cut'],'Bleeding stopped; patient cleaned it and feels well.',70,99,98.2,114,70,14,'stable','The bleeding has stopped and all fictional observations are steady.']
].map(([id,age,symptoms,scenario,heartRate,spo2,temperature,systolicBP,diastolicBP,respiratoryRate,correctTriage,educationalReason],index)=>({id,age,symptoms,scenario,heartRate,spo2,temperature,systolicBP,diastolicBP,respiratoryRate,correctTriage,educationalReason,difficulty:index%5===0||['146','417','098','192','284','410','129','223','326'].includes(id)?'codeblue':index%3===0?'student':'resident'}));
const triageLabel = { stable:'Stable', urgent:'Urgent', emergency:'Emergency' };
patients.forEach(patient => {
  /* Built-in feedback stays useful when the optional local enhancement is unavailable. */
  patient.educationalReason += ` This is why the fictional case is classified as ${triageLabel[patient.correctTriage]}, not as a diagnosis or treatment recommendation.`;
});
